name: local_websocket
description: A pure Dart library for local network WebSocket communication with automatic server discovery and scanning capabilities.
version: 0.0.2
repository: https://github.com/FlameOfUdun/local_websocket

environment:
  sdk: ^3.6.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.26.2
