name: flutter_local_websocket
description: Flutter plugin for local websocket communication.
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  shelf: ^1.4.2
  shelf_web_socket: ^3.0.0
  shelf_router: ^1.1.4
  web_socket_channel: ^3.0.2
  uuid: ^4.5.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
