name: flutter_local_websocket
description: Flutter plugin for local websocket communication.
version: 0.0.1

environment:
  sdk: ^3.6.2

dependencies:
  shelf: ^1.4.2
  shelf_web_socket: ^3.0.0
  shelf_router: ^1.1.4
  web_socket_channel: ^3.0.2
  dio: ^5.8.0+1
  uuid: ^4.5.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.26.2
